services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin                  
    command: start-dev
    ports:
      - "8081:8080"
